/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TugasPertemuan9;
//Berfungsi untuk menampilkan menu opsi
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class AplikasiKalkulator extends javax.swing.JFrame {
    //Deklarasi Variabel
    double angka1;//Untuk angka Pertama
    double angka2;//Untuk angka Kedua
    double hasil;//Untuk hasil dari perhitungan
    String perhitungan;//untuk jenis perhitungan yang akan dilakukan
    boolean isEqualstekan = false;
    /**
     * Creates new form AplikasiKalkulator
     */
    public AplikasiKalkulator() {
        initComponents();
    }
    //Method untuk tombol angka
    private void masukkanAngka(String angka){
        if(isEqualstekan == true){
            HASIL.setText("");
            isEqualstekan = false;
        }
        String ag = HASIL.getText() + angka;
        HASIL.setText(ag);
    }
    //Method untuk jenis perhitungan yang akan dilakukan
    private void perhitungan(String pr){
        angka1 = Double.parseDouble(HASIL.getText());
        HASIL.setText("");
        perhitungan = pr;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        HASIL = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BTN8 = new javax.swing.JButton();
        BTN4 = new javax.swing.JButton();
        BTN1 = new javax.swing.JButton();
        BTNcomma = new javax.swing.JButton();
        BTN7 = new javax.swing.JButton();
        BTN5 = new javax.swing.JButton();
        BTN2 = new javax.swing.JButton();
        BTN0 = new javax.swing.JButton();
        BTN9 = new javax.swing.JButton();
        BTN6 = new javax.swing.JButton();
        BTN3 = new javax.swing.JButton();
        BTNCLEAR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BTNPLUS = new javax.swing.JButton();
        BTNEQ = new javax.swing.JButton();
        BTNTIME = new javax.swing.JButton();
        BTNBACK = new javax.swing.JButton();
        BTNMINUS = new javax.swing.JButton();
        BTNDIVIDE = new javax.swing.JButton();
        BTNMOD = new javax.swing.JButton();
        BTNEX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        HASIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HASILActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(HASIL, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HASIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        BTN8.setText("8");
        BTN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN8ActionPerformed(evt);
            }
        });

        BTN4.setText("4");
        BTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN4ActionPerformed(evt);
            }
        });

        BTN1.setText("1");
        BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN1ActionPerformed(evt);
            }
        });

        BTNcomma.setText(".");
        BTNcomma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcommaActionPerformed(evt);
            }
        });

        BTN7.setText("7");
        BTN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN7ActionPerformed(evt);
            }
        });

        BTN5.setText("5");
        BTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN5ActionPerformed(evt);
            }
        });

        BTN2.setText("2");
        BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN2ActionPerformed(evt);
            }
        });

        BTN0.setText("0");
        BTN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN0ActionPerformed(evt);
            }
        });

        BTN9.setText("9");
        BTN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN9ActionPerformed(evt);
            }
        });

        BTN6.setText("6");
        BTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN6ActionPerformed(evt);
            }
        });

        BTN3.setText("3");
        BTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN3ActionPerformed(evt);
            }
        });

        BTNCLEAR.setText("C");
        BTNCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCLEARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN8, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(BTN4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNcomma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(BTN5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN9, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(BTN3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNCLEAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN8)
                    .addComponent(BTN7)
                    .addComponent(BTN9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTN4)
                        .addComponent(BTN6))
                    .addComponent(BTN5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN2)
                    .addComponent(BTN1)
                    .addComponent(BTN3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN0)
                    .addComponent(BTNcomma)
                    .addComponent(BTNCLEAR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        BTNPLUS.setText("+");
        BTNPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPLUSActionPerformed(evt);
            }
        });

        BTNEQ.setText("=");
        BTNEQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEQActionPerformed(evt);
            }
        });

        BTNTIME.setText("*");
        BTNTIME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTIMEActionPerformed(evt);
            }
        });

        BTNBACK.setText("B");
        BTNBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBACKActionPerformed(evt);
            }
        });

        BTNMINUS.setText("-");
        BTNMINUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMINUSActionPerformed(evt);
            }
        });

        BTNDIVIDE.setText("/");
        BTNDIVIDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDIVIDEActionPerformed(evt);
            }
        });

        BTNMOD.setText("%");
        BTNMOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMODActionPerformed(evt);
            }
        });

        BTNEX.setText("E");
        BTNEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNPLUS, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(BTNTIME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNEQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNBACK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNMINUS, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(BTNDIVIDE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNMOD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNEX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNPLUS)
                    .addComponent(BTNMINUS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNTIME)
                    .addComponent(BTNDIVIDE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNEQ)
                    .addComponent(BTNMOD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNBACK)
                    .addComponent(BTNEX))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Method untuk Layar HASIL
    private void HASILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HASILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HASILActionPerformed
    //Method Tombol 1
    private void BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN1ActionPerformed
        // TODO add your handling code here:
        masukkanAngka("1");
    }//GEN-LAST:event_BTN1ActionPerformed
    //Method Tombol 2
    private void BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN2ActionPerformed
        // TODO add your handling code here:
        masukkanAngka("2");
    }//GEN-LAST:event_BTN2ActionPerformed
    //Method Tombol 3
    private void BTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN3ActionPerformed
        // TODO add your handling code here:
        masukkanAngka("3");
    }//GEN-LAST:event_BTN3ActionPerformed
    //Method Tombol 4
    private void BTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN4ActionPerformed
        // TODO add your handling code here:
        masukkanAngka("4");
    }//GEN-LAST:event_BTN4ActionPerformed
    //Method Tombol 5
    private void BTN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN5ActionPerformed
        // TODO add your handling code here:
        masukkanAngka("5");
    }//GEN-LAST:event_BTN5ActionPerformed
    //Method Tombol 6
    private void BTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN6ActionPerformed
        // TODO add your handling code here:
        masukkanAngka("6");
    }//GEN-LAST:event_BTN6ActionPerformed
    //Method Tombol 8
    private void BTN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN8ActionPerformed
        // TODO add your handling code here:
        masukkanAngka("8");
    }//GEN-LAST:event_BTN8ActionPerformed
    //Method Tombol 7
    private void BTN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN7ActionPerformed
        // TODO add your handling code here:
        masukkanAngka("7");
    }//GEN-LAST:event_BTN7ActionPerformed
    //Method Tombol 9
    private void BTN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN9ActionPerformed
        // TODO add your handling code here:
        masukkanAngka("9");
    }//GEN-LAST:event_BTN9ActionPerformed
    //Method Tombol . atau Comma
    private void BTNcommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcommaActionPerformed
        // TODO add your handling code here:
        if(!HASIL.getText().contains(".")){
            HASIL.setText(HASIL.getText() + BTNcomma.getText());
        }
    }//GEN-LAST:event_BTNcommaActionPerformed
    //Method Tombol 0
    private void BTN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN0ActionPerformed
        // TODO add your handling code here:
        masukkanAngka("0");
    }//GEN-LAST:event_BTN0ActionPerformed
    //Method untuk Tombol Clear atau C beguna untuk menghapus angka semua yang ada pada layar HASIL
    private void BTNCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCLEARActionPerformed
        // TODO add your handling code here:
        HASIL.setText("");
        angka1 = 0;
        angka2 = 0;
    }//GEN-LAST:event_BTNCLEARActionPerformed
    //Method Tombol Tambah
    private void BTNPLUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPLUSActionPerformed
        // TODO add your handling code here:
        perhitungan("+");
    }//GEN-LAST:event_BTNPLUSActionPerformed
    //Method Tombol Kurang
    private void BTNMINUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMINUSActionPerformed
        // TODO add your handling code here:
        perhitungan("-");
    }//GEN-LAST:event_BTNMINUSActionPerformed
    //Method Tombol Kali
    private void BTNTIMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTIMEActionPerformed
        // TODO add your handling code here:
        perhitungan("*");
    }//GEN-LAST:event_BTNTIMEActionPerformed
    //Method Tombol Bagi
    private void BTNDIVIDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDIVIDEActionPerformed
        // TODO add your handling code here:
        perhitungan("/");
    }//GEN-LAST:event_BTNDIVIDEActionPerformed
    //Method Tombol Modulus
    private void BTNMODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMODActionPerformed
        // TODO add your handling code here:
        perhitungan("%");
    }//GEN-LAST:event_BTNMODActionPerformed
    //Method untuk tombol sama dengan atau = berfungsi untuk perhitungan apabila menggunakan tombol tambah dan sebagainya
    private void BTNEQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEQActionPerformed
        // TODO add your handling code here:
        angka2 = Double.parseDouble(HASIL.getText());
        if(perhitungan.equals("+")){
            hasil = angka1 + angka2;
            HASIL.setText(String.valueOf(hasil));
        }else if (perhitungan.equals("-")){
            hasil = angka1 - angka2;
            HASIL.setText(String.valueOf(hasil));
        }else if (perhitungan.equals("*")){
            hasil = angka1 * angka2;
            HASIL.setText(String.valueOf(hasil));
        }else if (perhitungan.equals("/")){
            if (angka2 != 0){
            hasil = angka1 / angka2;
            HASIL.setText(String.valueOf(hasil));
            }else {
                HASIL.setText("Hasil Tidak Terdefinisi");
            }
        } else {
            hasil = angka1 % angka2;
            HASIL.setText(String.valueOf(hasil));
        }
    }//GEN-LAST:event_BTNEQActionPerformed
    //Method untuk Tombol BACK atau B Berfungsi untuk Menghapus angka tapi tidak semua hanya 1 karakter
    private void BTNBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBACKActionPerformed
        // TODO add your handling code here:
        int uk = HASIL.getText().length();
        if(uk > 0){
            char[] ag = new char[uk-1];
             for(int j = 0; j < uk-1; j++){
                 ag[j] = HASIL.getText().charAt(j);
             }
             String angkaBaru = new String(ag);
             HASIL.setText(angkaBaru);
        }
    }//GEN-LAST:event_BTNBACKActionPerformed
    //Method Untuk Tombol Keluar atau E Berfungsi untuk keluar dari Program GUI
    private void BTNEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEXActionPerformed
        // TODO add your handling code here:
        int tampil = JOptionPane.showConfirmDialog(
                  null, "Apakah Anda Yakin ingin keluar?", "Konfirmasi Keluar Aplikasi",
                  JOptionPane.YES_NO_OPTION);
                  getToolkit().beep();//Berfungsi Menghasilkan bunyi
            if(tampil == JOptionPane.YES_OPTION){
                    System.exit(0);
            }else{
                HASIL.requestFocus();
            }
    }//GEN-LAST:event_BTNEXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN0;
    private javax.swing.JButton BTN1;
    private javax.swing.JButton BTN2;
    private javax.swing.JButton BTN3;
    private javax.swing.JButton BTN4;
    private javax.swing.JButton BTN5;
    private javax.swing.JButton BTN6;
    private javax.swing.JButton BTN7;
    private javax.swing.JButton BTN8;
    private javax.swing.JButton BTN9;
    private javax.swing.JButton BTNBACK;
    private javax.swing.JButton BTNCLEAR;
    private javax.swing.JButton BTNDIVIDE;
    private javax.swing.JButton BTNEQ;
    private javax.swing.JButton BTNEX;
    private javax.swing.JButton BTNMINUS;
    private javax.swing.JButton BTNMOD;
    private javax.swing.JButton BTNPLUS;
    private javax.swing.JButton BTNTIME;
    private javax.swing.JButton BTNcomma;
    private javax.swing.JTextField HASIL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
